fix compilation error for vaip (#236)
# Summary of Changes

fix compilation error for vaip build, build error was introduced by #204

see PR VitisAI/vaip#5018 also

# Motivation

```
vaip-core/src/vitisai_compile_model.cpp:1049:34: error: ‘kOrtSessionOptionsDisableModelCompile’ was not declared in this scope; did you mean ‘kOrtSessionOptionsDisableQuantQDQ’?
 1049 |   if (context.get_session_config(kOrtSessionOptionsDisableModelCompile, "1") ==
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  kOrtSessionOptionsDisableQuantQDQ
```

# Implementation

not to use `kOrtSessionOptionsDisableModelCompile`, it was introduced by
https://github.com/microsoft/onnxruntime/pull/24416

---------

Co-authored-by: Wang Chunye <chunywan@amd.com>